ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - init: >
      gem update --system && gem install bundler && bundler update --bundler && 
      bundle install --without production &&
      rails db:migrate
    command: >
      rails server
github:
    prebuilds:
        pullRequestsFromForks: true
